name: Automated Tests - Sauce Demo

on:
  workflow_dispatch:
    inputs:
      adminEnvironmentUrl:
        default: "https://www.saucedemo.com/v1/"
        description: "Sauce Demo Automation"
        required: true
      testSelection:
        description: "Select the tests to run"
        required: true
        type: choice
        options:
          - "All"
          - "Login"
          - "Inventory"

env:
  DOMAIN_ADMIN: https://www.saucedemo.com/v1/
  PATH_ADMIN: sauce-demo-automation
  TEST_PATH: ""

jobs:
  cypress-tests:
    name: Automation - ${{ github.event.inputs.testSelection }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Test Path
        run: |
          case "${{ github.event.inputs.testSelection }}" in
            "Inventory")
              echo "TEST_PATH=cypress/e2e/inventory.cy.jsx" >> $GITHUB_ENV
              ;;
            "Login")
              echo "TEST_PATH=cypress/e2e/login.cy.jsx" >> $GITHUB_ENV
              ;;
            "All")
              echo "TEST_PATH=cypress/e2e/**/*.cy.{js,jsx}" >> $GITHUB_ENV
              ;;
          esac

      - name: Set Dynamic Job Name
        run: echo "JOB_NAME=Automated Tests - Sauce Demo - ${{ github.event.inputs.testSelection }}" >> $GITHUB_ENV

      - name: Install dependencies and Execute Cypress Tests
        run: |
          npm install
          export CYPRESS_BASE_URL=https://www.saucedemo.com/v1/
          if [[ "${{ github.event.inputs.testSelection }}" == "All" ]]; then
            npm run cypress:run
          else
            npm run cypress:run -- --spec "${{ env.TEST_PATH }}"
          fi
